// <auto-generated/>
using Microsoft.JSInterop;

namespace UI.Components;

public partial class Home
{

    protected override async void OnAfterRender(bool firstRender)
    {        
        if (firstRender)
            await Js.InvokeVoidAsync("_highlightAll");
    }
}
