// <auto-generated/>
using Microsoft.JSInterop;

namespace UI.Components.Colors;

public partial class Colors
{
    string color = "";
    protected async override void OnAfterRender(bool firstRender)
    {
        if (firstRender)
        {
            color = await LocalStorage.GetItemAsStringAsync("Color");
            StateHasChanged();
        }
    }

    private async void SetColor(string colorName)
    {
        await Js.InvokeVoidAsync("SetTheme", colorName);
        color = colorName;
        StateHasChanged();
    }
}
