// <auto-generated/>
using Microsoft.AspNetCore.Components;
using Microsoft.JSInterop;

namespace UI.Components.Pages.Colors;

public partial class Colors
{
    string color = "#3a7bd5", mode = "light";
    ElementReference code;


    protected async override void OnAfterRender(bool firstRender)
    {
        if (firstRender)
        {
            color = await LocalStorage.GetItemAsStringAsync("Color");
            if (!string.IsNullOrEmpty(color))
            {
                if (color.StartsWith("#"))
                    color = color.Split(' ')[0];
            }

            StateHasChanged();
        }
    }

    private async void SetColor(string colorName)
    {
        await Js.InvokeVoidAsync("SetTheme", colorName);
        color = colorName;
        StateHasChanged();
    }

    private void ChangeMode(string _mode)
    {
        mode = _mode;
    }

    private async void GenerateNewTheme()
    {
        await Js.InvokeVoidAsync("GenerateTheme", color, mode, code);
    }
}
